### ISSUE TITLE
finetune local embedding model from huggingface with llama_index 

### ISSUE THREAD

**Issue by zzzcccxx** [AjayK47/Web-Page-ChatBot-using-Llama-index#1]
Hi, thanks for sharing. I would like to ask if I want to use llama_index to fine-tune the embedding model locally or huggingface, what should I do?

**Comment by AjayK47** [comment]
hey there! as far i am aware , i don't have knowledge on fine-tuning with Llama-index. maybe it is not possible , i always thought of llama-index mainly aimed to help make RAG applications. make sure to check their docs maybe if it is possible.
